---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  labels:
    app: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      name: checkoutservice
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: checkoutservice
          image: 9952268641/gcr:checkoutservice
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
          env:
            - name: PORT
              value: "5050"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
            - name: CART_SERVICE_ADDR
              value: "cartservice:7070"
            - name: CURRENCY_SERVICE_ADDR
              value: "currencyservice:7000"
            - name: EMAIL_SERVICE_ADDR
              value: "emailservice:8080"
            - name: PAYMENT_SERVICE_ADDR
              value: "paymentservice:50051"
            - name: SHIPPING_SERVICE_ADDR
              value: "shippingservice:50051"      
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  selector:
    app: checkoutservice
  type: ClusterIP
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP