---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      name: emailservice
      labels:
        app: emailservice
    spec:
      containers:
        - name: emailservice
          image: 9952268641/gcr:emailservice
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT 
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  selector:
    app: emailservice
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP