---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      name: paymentservice
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: 9952268641/gcr:paymentservice
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            - name: PORT 
              value: "50051"
            - name: DISABLE_PROFILER
              value: "1"
      
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  selector:
    app: paymentservice
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP