---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  labels:
    app: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      name: recommendationservice
      labels:
        app: recommendationservice
    spec:
      containers:
        - name: recommendationservice
          image: 9952268641/gcr:recommendationservice
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT 
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  selector:
    app: recommendationservice
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 8080
      protocol: TCP